# --- Reglas para Wofi ---
# Evita que Hyprland dibuje bordes o sombras en la caja cuadrada invisible
windowrule = noborder, class:^(wofi)$
windowrule = noshadow, class:^(wofi)$

# Si Hyprland trata a Wofi como una capa (layer shell), esto evita que el blur
# oscurezca las esquinas transparentes
layerrule = ignorealpha 0.5, wofi
layerrule = blur, wofi # (Opcional, por si quieres que el fondo sea translúcido)
