# 2. Reglas de ventana para que se vea genial
# Le damos una "clase" específica (notas_term) para que Hyprland sepa cómo tratarla
windowrule = float on, match:workspace especial:notas
windowrule = size 70% 70%, match:workspace especial:notas
windowrule = center on, match:workspace especial:notas
windowrule = animation popin, match:workspace especial:notas # Animación de aparición rápida
