--enable-features=UseOzonePlatform
--ozone-platform=wayland
--enable-wayland-ime
--disable-gpu
--disable-software-rasterizer
--no-sandbox
--disable-dev-shm-usage
--disable-background-networking
--disable-sync
--disable-translate
--disable-back-forward-cache
--disable-features=TranslateUI,MediaRouter,PreloadMediaEnginesData
--disable-ipc-flooding-protection
--disable-renderer-backgrounding
--disable-background-timer-throttling
--disable-backgrounding-occluded-windows
--disable-hang-monitor
--disable-prompt-on-repost
--disable-popup-blocking
--disable-extensions
--disable-component-extensions-with-background-pages
--disable-component-update
--disable-default-apps
--disable-logging
--disable-crash-reporter
--disable-in-process-stack-dumps
--no-first-run
--no-default-browser-check
--safebrowsing-disable-auto-update
--metrics-recording-only
--disable-background-networking
--disable-sync
--disable-translate
--disable-default-apps
--ignore-gpu-blocklist
--enable-features=VaapiVideoDecoder
--use-gl=swiftshader
--disable-images
--disable-font-subpixel-positioning
--disable-canvas-aa
--disable-2d-canvas-clip-aa
--disable-webgl
--enable-features=VizDisplayCompositor
--disable-accelerated-2d-canvas
--disable-accelerated-video-decode
--disable-gpu-compositing
