--enable-features=UseOzonePlatform
--ozone-platform=wayland
--enable-wayland-ime
--password-store=basic
--disable-gpu
--disable-software-rasterizer
--no-sandbox
--disable-dev-shm-usage
--disable-background-networking
--disable-sync
--disable-translate
--disable-back-forward-cache
--disable-features=TranslateUI
--disable-ipc-flooding-protection
--disable-renderer-backgrounding
--disable-background-timer-throttling
--disable-backgrounding-occluded-windows
--disable-hang-monitor
--disable-prompt-on-repost
--disable-popup-blocking
--disable-extensions
--disable-component-extensions-with-background-pages
--disable-component-update
--disable-default-apps
--disable-logging
--disable-crash-reporter
--disable-in-process-stack-dumps
--no-first-run
--no-default-browser-check
--safebrowsing-disable-auto-update
--metrics-recording-only
--disable-extensions
--disable-background-networking
--disable-default-apps
--disable-sync
--disable-translate
--single-process
--js-flags=--jitless --no-expose-wasm
--ignore-gpu-blocklist
--enable-features=VaapiVideoDecoder
--use-gl=swiftshader
