##############################################################
## Tema: Catppuccin (Mocha)                                 ##
## Descripción: Paleta pastel, suave y moderna              ##
##############################################################

# Backgrounds (Tonos oscuros)
$bg0 = 11111B # crust (Más oscuro)
$bg1 = 1E1E2E # base (Fondo principal)
$bg2 = 313244 # surface0
$bg3 = 45475A # surface1
$bg4 = 585B70 # surface2

# Foreground (Texto principal)
$fg  = CDD6F4 # text

# Colores Principales
$red    = F38BA8 # red
$orange = FAB387 # peach
$yellow = F9E2AF # yellow
$green  = A6E3A1 # green
$aqua   = 94E2D5 # teal
$blue   = 89B4FA # blue
$purple = CBA6F7 # mauve
$pink   = F5C2E7 # pink

# Grises (Para bordes, comentarios o fondos inactivos)
$grey0 = 9399B2 # overlay2
$grey1 = 7F849C # overlay1
$grey2 = 6C7086 # overlay0
