##############################################################
## Tema: Everforest (Dark)                                  ##
## Descripción: Paleta natural, cálida y relajante          ##
##############################################################

# Backgrounds (Tonos oscuros)
$bg0 = 232A2E # darkest background
$bg1 = 2D353B # main background
$bg2 = 343F44 # surface0
$bg3 = 3D484D # surface1
$bg4 = 475258 # surface2

# Foreground (Texto principal)
$fg  = D3C6AA # text

# Colores Principales
$red    = E67E80 # red
$orange = E69875 # orange
$yellow = DBBC7F # yellow
$green  = A7C080 # green
$aqua   = 83C092 # aqua
$blue   = 7FBBB3 # blue
$purple = D699B6 # purple
$pink   = E698B4 # pink

# Grises (Para bordes, comentarios o fondos inactivos)
$grey0 = 859289 # grey2
$grey1 = 7A8478 # grey1
$grey2 = 6F7A6F # grey0
