##############################################################
## Tema: Gruvbox                                            ##
## Descripción: Paleta retro con contraste cálido           ##
##############################################################

# Backgrounds (Tonos oscuros)
$bg0 = 282828 # bg_dim (Más oscuro)
$bg1 = 3C3836 # bg1 (Fondo principal)
$bg2 = 504945 # bg2
$bg3 = 665C54 # bg3
$bg4 = 7C6F64 # bg4

# Foreground (Texto principal)
$fg  = EBDBB2 # fg principal

# Colores Principales
$red    = CC241D # red
$orange = D65D0E # orange
$yellow = D79921 # yellow
$green  = 98971A # green
$aqua   = 689D6A # aqua
$blue   = 458588 # blue
$purple = B16286 # purple
$pink   = D3869B # bright purple (usado como rosa en Gruvbox)

# Grises (Para bordes, comentarios o fondos inactivos)
$grey0 = A89984 # gray claro
$grey1 = 928374 # gray medio
$grey2 = 7C6F64 # gray oscuro
