##############################################################
## Tema: Kanagawa                                           ##
## Descripción: Paleta de colores cálida y suave (Sumi Ink) ##
##############################################################

# Backgrounds (Tonos Sumi Ink)
$bg0 = 16161D # sumiInk0 (Más oscuro)
$bg1 = 1F1F28 # sumiInk1 (Fondo principal)
$bg2 = 2A2A37 # sumiInk2
$bg3 = 363646 # sumiInk3
$bg4 = 54546D # sumiInk4

# Foreground (Texto principal)
$fg  = DCD7BA # fujiWhite

# Colores Principales
$red    = C34043 # samuraiRed
$orange = FFA066 # surimiOrange
$yellow = E6C384 # springYellow
$green  = 98BB6C # autumnGreen
$aqua   = 7AA89F # waveAqua1
$blue   = 7E9CD8 # crystalBlue
$purple = 957FB8 # oniViolet
$pink   = D27E99 # sakuraPink

# Grises (Para bordes, comentarios o fondos inactivos)
$grey0 = 727169 # fujiGray
$grey1 = 717C7C # katanaGray
$grey2 = 536161 # masonryGray
